// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWnsOUtXqcVhBBFJVe7LrrNB7ZWLzoC6A',
    appId: '1:401393361442:web:79be8dde5290419ba8a07b',
    messagingSenderId: '401393361442',
    projectId: 'gym-tracker-2026',
    authDomain: 'gym-tracker-2026.firebaseapp.com',
    storageBucket: 'gym-tracker-2026.firebasestorage.app',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLXO5yd6MwDHeW_rvSNk0A-TcoIOJU4s4',
    appId: '1:401393361442:android:49f65c7e6db4c456a8a07b',
    messagingSenderId: '401393361442',
    projectId: 'gym-tracker-2026',
    storageBucket: 'gym-tracker-2026.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsZ00NzlKPSa7UmUaHZRLl3dLmFqxKF0U',
    appId: '1:401393361442:ios:5f9d20f0b3bcfabfa8a07b',
    messagingSenderId: '401393361442',
    projectId: 'gym-tracker-2026',
    storageBucket: 'gym-tracker-2026.firebasestorage.app',
    iosBundleId: 'com.mainor.gymtracker.gymTracker',
  );
}
